apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-repo
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      exclude: base-repo.yaml
      include: '*.yaml'
    path: .
    repoURL: https://github.com/LilithPandragon/my-new-gitops-repo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
